declare module 'remark-capitalize'
declare module 'remark-code-titles'
declare module 'remark-copy-linked-files'
declare module 'remark-prism'
declare module '@mapbox/rehype-prism'
declare module 'rehype-slug'
declare module 'rehype-autolink-headings'
declare module 'rehype-add-classes'
